# Generated by Django 3.2.7 on 2021-11-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='topping',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
