# Generated by Django 3.2.7 on 2021-11-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20211110_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='ЧПУ'),
        ),
    ]
