# Generated by Django 3.2.7 on 2021-11-13 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizza', '0003_pizza_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(null=True, upload_to='pizza_image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='recipe',
            field=models.ManyToManyField(to='pizza.Topping', verbose_name='ингредиенты'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='title',
            field=models.CharField(max_length=30, verbose_name='название'),
        ),
    ]
